[supervisord]
nodaemon=true

[program:laravel-octane]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan octane:start --host=0.0.0.0 --port=9000 --workers=8 --server=swoole
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-octane.log

[program:laravel-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=default --timeout=30 --backoff=1
autostart=true
autorestart=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-queue-default.log

[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-scheduler.log

